=== 0xEAB/dplug/plugin-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Dplug plugin.json schema",
    "type": "object",

    "required": [ "CFBundleIdentifierPrefix",
                  "hasGUI",
                  "isSynth",
                  "pluginName",
                  "pluginUniqueID",
                  "publicVersion",
                  "receivesMIDI",
                  "vendorName",
                  "vendorUniqueID",
                  "category" ],

    "properties": {
        "CFBundleIdentifierPrefix": {
            "description": "Mandatory prefix for macOS bundles.",
            "id": "/properties/CFBundleIdentifierPrefix",
            "type": "string"
        },
        "developerIdentity-osx" : {
            "description": "The signing identity used when code-signing for macOS. Mandatory for Mac installers.",
            "id": "/properties/developerIdentity-osx",
            "type": "string"
        },
        "iconPath": {
            "description": "Very optional path to an icon file, to be used for macOS bundles. Not sure if working.",
            "id": "/properties/commented-iconPath",
            "type": "string"
        },
        "installerPNGPath" : {
            "description": "The .png background path used for Mac installers. Optional.",
            "id": "/properties/installerPNGPath",
            "type": "string"
        },
        "hasGUI": {
            "description": "true if the plug-in has a GUI. Can be used to disabled the UI of a plug-in.",
            "id": "/properties/hasGUI",
            "type": "boolean"
        },
        "isSynth": {
            "description": "true if the plug-in is an instrument. Must match with the choosen category property.",
            "id": "/properties/isSynth",
            "type": "boolean"
        },
        "licensePath": {
            "description": "Optional path to a license file, to be bundled with binary releases.",
            "id": "/properties/licensePath",
            "type": "string"
        },
        "pluginName": {
            "description": "Full name of the plug-in vendor.",
            "id": "/properties/pluginName",
            "type": "string"
        },
        "pluginUniqueID": {
            "description": "A four char code identifying your plug-in in the VST2 namespace. Nobody knows which one are available or not. When breaking save compatibility, you MUST issue a new plugin ID.",
            "id": "/properties/pluginUniqueID",
            "type": "string"
        },
        "publicVersion": {
            "description": "Public version of the plug-in, of the form major.minor.patch. The implicit meaning is that save compatibility is broken only for major versions.",
            "id": "/properties/publicVersion",
            "type": "string"
        },
        "receivesMIDI": {
            "description": "true if the plug-in reads MIDI input, can be for a synthesizer or an effect taking MIDI.",
            "id": "/properties/receivesMIDI",
            "type": "boolean"
        },
        "userManualPath": {
            "description": "Optional path to a user manual file, to be bundled with binary releases.",
            "id": "/properties/userManualPath",
            "type": "string"
        },
        "vendorName": {
            "description": "The full name of the plug-in vendor.",
            "id": "/properties/vendorName",
            "type": "string"
        },
        "vendorUniqueID": {
            "description": "A four char code for the plug-in vendor.",
            "id": "/properties/vendorUniqueID",
            "type": "string"
        },
        "category": {
            "description": "The category of the plug-in. Helps to be listed more prominently in a DAW.",
            "id": "/properties/category",
            "type": "string",

            "enum": [

                "effectAnalysisAndMetering",
                "effectDelay",
                "effectDistortion",
                "effectDynamics",
                "effectEQ",
                "effectImaging",
                "effectModulation",
                "effectPitch",
                "effectReverb",
                "effectOther",

                "instrumentDrums",
                "instrumentSampler",
                "instrumentSynthesizer",
                "instrumentOther"
            ]
        }
    }
}

=== 0xEAB/dplug/tests/using-runtime/plugin.json
{
    "$schema": "https://raw.githubusercontent.com/AuburnSounds/dplug/master/plugin-schema.json",

    "vendorName": "No Name Audio",
    "vendorUniqueID": "NoAu",
    "pluginName": "Runtime User",
    "pluginUniqueID": "NAru",
    "publicVersion": "1.0.0",
    "CFBundleIdentifierPrefix": "com.nonameaudio",
    "hasGUI": false,
    "isSynth": false,
    "receivesMIDI": false,
    "category": "effectOther"
}

=== 0xEAB/dplug/examples/sample-meter/plugin.json
{
    "$schema": "https://raw.githubusercontent.com/AuburnSounds/dplug/master/plugin-schema.json",

    "vendorName": "No Name Audio",
    "vendorUniqueID": "NoAu",
    "pluginName": "Sample Meter",
    "pluginUniqueID": "SpÂ°",
    "publicVersion": "1.0.0",
    "CFBundleIdentifierPrefix": "om.nonameaudio",
    "hasGUI": false,
    "isSynth": false,
    "receivesMIDI": false,
    "category": "effectAnalysisAndMetering"
}
